version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: auth_artex
    restart: always
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: artex
      POSTGRES_PASSWORD: artex
    ports:
      - "5477:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
