# Generated by Django 5.1.4 on 2024-12-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='stand_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
